--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/ClearLagg
build-by-default: true
branches:
- main
- 1.1.0
projects: 
  ClearLagg:
    path: ""
    icon: "https://i.ibb.co.com/gW2N2Hz/OIG1-removebg-preview.png"
...
