name: ClearLagg
api: 5.0.0
version: 1.0.0-Beta
author: XPocketMC
























































































































































































































































































































































































































































































































































































































































































































































































































































main: ClearLagg\Main
commands:
  clearlagg:
    description: Clears all dropped items
    usage: "/clearlagg"
permissions: 
  clearlagg.use:
    default: true
    description: Allows the player to use the /clearlag command
