name: Build ClearLagg Plugin and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/xpocketmc/clearlagg:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/xpocketmc/clearlagg:latest

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          files: builds/ClearLagg.phar
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        run: echo "Release ID is ${{ steps.create_release.outputs.id }}"

      - name: Publish Package
        run: echo "Publishing package..."

      - name: Set Package ID
        id: set_package_id
        run: echo "::set-output name=package_id::$(uuidgen)"

      - name: Notify Package ID
        run: echo "Package ID is ${{ steps.set_package_id.outputs.package_id }}"
