name: Build ClearLagg Plugin and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Download PocketMine-MP.phar
        run: wget -q -O PocketMine-MP.phar https://github.com/pmmp/PocketMine-MP/releases/latest/download/PocketMine-MP.phar

      - name: Create plugins/ClearLagg directory
        run: mkdir -p plugins/ClearLagg

      - name: Copy source files to plugins/ClearLagg
        run: cp -R src/* plugins/ClearLagg/

      - name: Copy plugin.yml to plugins/ClearLagg
        run: cp plugin.yml plugins/ClearLagg/

      - name: Build ClearLagg Plugin
        run: |
          cd plugins
          php ../PocketMine-MP.phar --make-plugin ClearLagg
          mv ClearLagg.phar ../builds/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          name: Release 1.0.0
          files: builds/ClearLagg.phar
          draft: false
          prerelease: false

      - name: Build Docker image
        run: |
          echo "FROM php:8.3-cli" > Dockerfile
          echo "RUN docker-php-ext-install mbstring xml" >> Dockerfile
          echo "COPY src /usr/src/myapp/src" >> Dockerfile
          echo "COPY plugin.yml /usr/src/myapp/" >> Dockerfile
          echo "ADD https://github.com/pmmp/PocketMine-MP/releases/latest/download/PocketMine-MP.phar /usr/src/myapp/PocketMine-MP.phar" >> Dockerfile
          echo "WORKDIR /usr/src/myapp" >> Dockerfile
          echo "RUN mkdir -p plugins/ClearLagg \\" >> Dockerfile
          echo "    && cp -R src/* plugins/ClearLagg/ \\" >> Dockerfile
          echo "    && cp plugin.yml plugins/ClearLagg/ \\" >> Dockerfile
          echo "    && php PocketMine-MP.phar --make-plugin ClearLagg \\" >> Dockerfile
          echo "    && mv ClearLagg.phar /usr/src/myapp/ClearLagg.phar" >> Dockerfile
          echo "CMD [\"php\", \"-v\"]" >> Dockerfile
          docker build -t ghcr.io/${{ github.repository_owner }}/clearlagg:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/clearlagg:latest
