name: Build and Release Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libzip-dev \
            unzip \
            git \
            autoconf \
            g++ \
            make

      - name: Update pecl.php.net channel
        run: pecl channel-update pecl.php.net

      - name: Install zip extension via pecl
        run: |
          sudo pecl install channel://pecl.php.net/zip-1.22.3
          docker-php-ext-enable zip

      - name: Install mbstring extension
        run: docker-php-ext-install mbstring

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name: Install dependencies with Composer
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Build plugin
        run: |
          mkdir -p build
          zip -r build/plugin.zip src

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-build
          path: build

      - name: Create Draft Release
        id: create_release
        uses: marvinpinto/github-action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set_version.outputs.version }}
          release_name: Release ${{ steps.set_version.outputs.version }}
          draft: true
          prerelease: false
