name: Build and Release ClearLagg Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Build plugin
        run: |
          mkdir -p build
          zip -r build/ClearLagg.zip . -x '.git/*' -x '.github/*' -x 'tests/*' -x 'build/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ClearLagg
          path: build/ClearLagg.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ClearLagg

      - name: Create Package
        run: |
          mkdir -p package
          cp build/ClearLagg.zip package/
          cd package
          zip -r ClearLagg-Package.zip ClearLagg.zip

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/ClearLagg.zip
            package/ClearLagg-Package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
