name: Build and Release ClearLagg Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Build plugin
        run: |
          mkdir -p build
          zip -r build/ClearLagg.zip . -x 'vendor/*' -x '.github/*' -x 'tests/*' -x '.git/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ClearLagg
          path: build/ClearLagg.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ClearLagg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ClearLagg.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
